### ISSUE TITLE
no moudle named django youtube_dl pychromecast

### ISSUE THREAD

**Issue by worldyouwyl** [harddevelop/googlehomeplayer#1]
I have pip3 it, why I can't use it in my anaconda.

**Comment by bitstuffing** [comment]
Sorry but, what is the bug? You opened a bug but your problem is you didn't install the requirements, right?

I think you should take a look in your pip3 installation to solve it, or reinstall with the official script.

https://bootstrap.pypa.io/get-pip.py

Required dependencies are very famous and very well known.

Modules are installed from global repositories so I think you should do one of these two things: or check your system or install dependencies each one by yourself. 

https://github.com/balloob/pychromecast

https://docs.djangoproject.com/en/2.1/topics/install/

https://rg3.github.io/youtube-dl/

I hope it helps you.
